version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: rohan
      POSTGRES_PASSWORD: rohan2939
      POSTGRES_DB: cms
    ports:
      - '5408:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  app:
    build: .
    container_name: nextjs_app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://rohan:rohan2939@postgres:5432/cms
    depends_on:
      - postgres

volumes:
  postgres_data:
